### ISSUE TITLE
Host stickers

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-site#41]
@floam commented on [Mon Aug 01 2016](https://github.com/fish-shell/fish-shell/issues/3278)

I have never noticed it before but there is a file [`doc_src/branding/logo.psd`](https://github.com/fish-shell/fish-shell/blob/master/doc_src/branding/logo.psd) checked into master. It's around 3.8MB large. We also have been including it in our [releases](https://github.com/fish-shell/fish-shell/releases/download/2.3.1/fish-2.3.1.tar.gz) it seems, where even after being gzipped it's making the tarball about a third larger than it'd otherwise be. It seems to me this would have a better home in a clean branch other than `master`, or better another repo entirely like `fish-site`.

The ~4MB PSD doesn't seem to represent the most official logo of fish (despite the filename), instead it seems to be a cool fan-art composition of the ASCII fish with a template for laser-cutters, for having stickers made. What's the thinking here? Nobody downloading fish will need it. Someone searching for fish stickers likely won't find it with it buried there. Shouldn't it go on the website, if anywhere?

---

@ridiculousfish commented on [Mon Aug 01 2016](https://github.com/fish-shell/fish-shell/issues/3278#issuecomment-236676088)

Oh god, how did that get in there. Yes, let's move it to fish-site.

---

@floam commented on [Mon Aug 01 2016](https://github.com/fish-shell/fish-shell/issues/3278#issuecomment-236698826)

I'll yank it. How do you want to show it on the actual site of fish-site? I suppose another way to do it is host it in the repo with the README pretty much like this one was and mention on Wiki or something. 

---

@ridiculousfish commented on [Mon Aug 01 2016](https://github.com/fish-shell/fish-shell/issues/3278#issuecomment-236700367)

I think interest in the artwork itself will be low, so it's OK to link to it from an obscure place (like the wiki). But users might like to have a place to buy stickers - that might merit a small link on the site.

---

@floam commented on [Mon Aug 01 2016](https://github.com/fish-shell/fish-shell/issues/3278#issuecomment-236702416)

OK, "moving" this issue over to fish-site with the magic button in this [browser extension](https://github.com/ZenHubIO/support)... It can be discussed there.

**Comment by floam** [comment]
I don't think very many people will make use of the stickers. But anyhow that has fish stickers, please take a photo of your deployed stickers you had printed and share them here, I'd be interested to see that.

**Comment by lee2sman** [comment]
Hi, I just wanted to say that because I couldn't find any official fish shell stickers I made my own. I used redbubble and it came out really well. I basically screenshotted the fish ascii logo in the terminal since the [official](https://github.com/fish-shell/fish-shell/blob/master/fish.png) (?) one is not print-quality size. Unless I'm missing something. I don't see the psd file in this repo nor its commit history.

I don't have my own redbubble page *live* because I think it would mean that if people bought one I'd get a small commission and I don't know if that's allowed but that means if others want stickers they'd have to manually do what I did.

![fish-sticker](https://user-images.githubusercontent.com/7377908/86538300-3678ad80-bec3-11ea-915e-dc409bc2248b.png)
