### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by Haroenv** [fish-shell/fish-site#55]
Hey 👋 I've been using `fish` since forever, but I keep needing to look up some differences with bash like how to set env variables for a single command. It would be really nice if I could search within the site for that. 

I'm working at Algolia and we offer [docsearch](https://community.algolia.com/docsearch) as a free service for open source projects. It basically crawls the documentation and makes it searchable, and you add an autocomplete to your page so people can search in it. 

Let me know if you're interested!

**Comment by ridiculousfish** [comment]
Sounds nifty! What's a good live example to try?

**Comment by Haroenv** [comment]
Https://reacts.org

**Comment by s-pace** [comment]
👋 As always, @Haroenv got a point.

Happy to help on this @ridiculousfish

A preview:
![preview of DocSearch](https://cl.ly/3a412t2h2o09/download/Screen%20Recording%202018-06-18%20at%2003.19%20PM.gif)

[You can try it out here](https://fishshell-docsearch.surge.sh/)

We do provide search analytics in order to enhance your doc if you want.

___

Congratulations, your search is now ready!
I've successfully configured the underlying crawler and it will now run every 24h.

You're now a few steps away from having it working on your website:

- Copy the following CSS/JS snippets and add them to your page

```html
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />

<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: 'ffed66937f1e00fb19bf61bc7845ab8d',
  indexName: 'fishshell',
  inputSelector: '### REPLACE ME ####',
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```
- Add a search input in your page if you don't have any yet. Then update the inputSelector value in JS snippet to a CSS selector that targets your search input field.
- Optionally customize the look and feel by following [the DocSearch documentation](https://community.algolia.com/docsearch/documentation/)
- You can also check your configuration [in our GitHub repo](https://github.com/algolia/docsearch-configs/blob/master/configs/fishshell.json).

Please open a pull request if want to leverage your configuration!

Feel free to get back to us if you have any issues or questions regarding the integration.

Have a nice day :)

**Comment by Haroenv** [comment]
https://docsearch-fishshell.netlify.com @ridiculousfish, we updated the demo, in case you're interested :)

**Comment by faho** [comment]
This is actually included in our new doc system based on sphinx, so it'll be in the 3.1 release.
