### ISSUE TITLE
install on Windows

### ISSUE THREAD

**Issue by paulvi** [fish-shell/fish-site#60]
I use git for Windows https://git-for-windows.github.io/ that comes with Bash shell.

However from http://fishshell.com/#get_fish_windows it is not clear how to install fish-shell.  
`pacman` is not available, and there is no any Setup options.

> $ pacman
> bash: pacman: command not found

**Comment by ridiculousfish** [comment]
Is it possible to install other packages with git for Windows? It's not clear to me if this is a general purpose development environment or something specific for git.

Also do the [build instructions](https://github.com/fish-shell/fish-shell/#building) work?

**Comment by paulvi** [comment]
Well, I cannot tell. I just can tell that Git Bash is the most installed on Windows shell,  
after Git popularity grew year by year.

**Comment by ridiculousfish** [comment]
Unfortunately I don't have the time to investigate what it would take to install fish on git for Windows. I'm going to close this since I don't think we have plans to address this.

(Of course if you or anyone wants to take it on and provide fixes / install instructions, that would be great and we'd be happy to include them on the site)

Thanks for filing!

**Comment by MoonLightElf** [comment]
#63
I recommend this question and answer. Then install fish via PacMan in msys2.
https://stackoverflow.com/questions/32712133/package-management-in-git-for-windows/60611888#60611888

**Comment by blaze-12** [comment]
i wonder why mine is not working

**Comment by blaze-12** [comment]
or does git bash has a problem
